stages:
  - build

build:
  tags:
    - linux
  stage: build
  variables:
    NEXUS_URL: http://kongrentian.com:8081
    DEPLOY_DIR: /var/nexus/deploy
    DATA_DIR: /var/nexus/data
  script:
    - mvn -P buildKar clean install
    - sudo cp target/nexus-security-plugin-*-bundle.kar "${DEPLOY_DIR}/"
    - sudo chown 200 "${DEPLOY_DIR}"/*
    - docker restart nexus
    - sleep 50
    - curl --fail "${NEXUS_URL}/repository/pypi/packages/pip/21.3.1/pip-21.3.1-py3-none-any.whl"
      || sudo tail -n 300 "${DATA_DIR}/log/nexus.log"
