stages:
  - build

build:
  tags:
    - linux
  stage: build
  variables:
    NEXUS_URL: http://kongrentian.com:8081
    DEPLOY_DIR: /var/nexus/deploy
    DATA_DIR: /var/nexus/data
  script:
    - ./mvnw -P buildKar clean verify --show-version --batch-mode --errors
    - chmod 777 target/*.kar
    - rm -f "${DEPLOY_DIR}"/*.kar
    - cp target/*.kar "${DEPLOY_DIR}/"
    - docker restart nexus
    - sleep 120
    - curl 
      --fail 
      --user "${NEXUS_LOGIN}:${NEXUS_PASSWORD}" 
      "${NEXUS_URL}/repository/pypi/packages/pip/21.3.1/pip-21.3.1-py3-none-any.whl"
      || tail -n 300 "${DATA_DIR}/log/nexus.log"
