stages:
  - test

build:
  tags:
    - linux
  stage: test
  variables:
    NEXUS_URL: http://kongrentian.com:8081
    DIRECTORY_DEPLOY: /var/nexus/deploy
    DIRECTORY_DATA: /var/nexus/data
  artifacts:
    paths:
      - target/*.kar
    when: always
  script:
    - ./mvnw -P buildKar clean verify --show-version --batch-mode --errors
    - chmod 777 target/*.kar
    - rm -f "${DIRECTORY_DEPLOY}"/*.kar
    - cp target/*.kar "${DIRECTORY_DEPLOY}/"
    - /usr/libexec/docker/cli-plugins/docker-compose
      up -d
    - docker restart nexus
    - sleep 120
    - curl
      --fail
      --user "${NEXUS_LOGIN}:${NEXUS_PASSWORD}"
      "${NEXUS_URL}/repository/pypi/packages/pip/21.3.1/pip-21.3.1-py3-none-any.whl"
      > /dev/null
      || fail_flag=True
    - tail -n 300 "${DIRECTORY_DATA}/log/nexus.log"
    - test "${fail_flag}" && exit 1
