version: "2"

services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    volumes:
      - "/var/nexus/data:/nexus-data"
      - "/var/nexus/deploy:/opt/sonatype/nexus/deploy"
    ports:
      - "8081:8081"