package com.kongrentian.plugins.nexus.model;

public enum ScanResultType {
    WHITE_LIST_CONTAINS_EXTENSION,
    WHITE_LIST_CONTAINS_USER,
    WHITE_LIST_CONTAINS_PACKAGE_VERSION,
    WHITE_LIST_CONTAINS_REPOSITORY,
    WHITE_LIST_CONTAINS_FORMAT,
    INVALID_LAST_MODIFIED,
    VALID_LAST_MODIFIED,
    EXCEPTION,
    EXCEPTION_IGNORED
}
