name: build

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - src
      - .github/**/*
  workflow_dispatch:

jobs:
  build:
    name: reuse-build
    uses: ./.github/workflows/reuse-build.yml
