name: build-local

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - src
      - .github/**/*

jobs:
  build:
    name: Reuse build
    uses: ./.github/workflows/build.yml
    with:
      version: LOCAL-SNAPSHOT-${{ github.sha }}-${{ github.run_attempt }}
